### ISSUE TITLE
Will sources be updated annually?

### ISSUE THREAD

**Issue by tvanantwerp** [TaxFoundation/sources-of-government-revenue#3]
Many of the datasets I'm using for country landing pages have many years of data. I don't know if this data set is intended to get annual updates in the future or not--I would assume the sources of revenue do change a bit year-to-year. If annual updates are intended, it would be good to go ahead and add a `year` column so I don't have to rewrite any fetching/munging code next year before the pages can be generated.

https://github.com/TaxFoundation/sources-of-government-revenue/blob/master/final-outputs/oecd_by_country.csv

**Comment by elkeasen** [comment]
Yes, this source will be updated annually. I added a `year` column.
